config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :letters do
    member do
      post :to_cancel
      post :to_work
      post :to_completed
    end
    collection do
      get :letter_statistics
      get :search_email
    end
  end
  devise_for :users
  root 'letters#page'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :user

  scope :search_by_email, -> (e_mail) { where email: e_mail }
  scope :last_half_year, -> { where('created_at > ?', Date.today.months_ago(6)) }

  scope :state_new, -> { where(aasm_state: 'new') }
  scope :state_canceled, -> { where(aasm_state: 'canceled') }
  scope :state_in_work, -> { where(aasm_state: 'in_work') }
  scope :state_completed, -> { where(aasm_state: 'completed') }

  include AASM
  aasm do
    state :new, initial: true
    state :canceled
    state :in_work
    state :completed

    event :to_cancel do
      transitions from: [:new, :in_work], to: :canceled
    end

    event :to_work do
      transitions from: [:new], to: :in_work
    end

    event :to_completed do
      transitions from: [:in_work], to: :completed
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :letters, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  before_action :configure_permitted_parameters, if: :devise_controller?

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale = :ru
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/letters_controller.rb
class LettersController < ApplicationController
  before_action :set_letter, only: [:show, :edit, :update, :destroy, :to_cancel, :to_work, :to_completed]

  def page
    if user_signed_in?
      redirect_to letters_path
    end
  end

  def index
    @letters = current_user.letters

    dates = params[:date] || {}
    @letters = @letters.where("created_at >= ?", dates[:start_date]) if dates[:start_date]
    @letters = @letters.where("created_at <= ?", dates[:end_date]) if dates[:end_date]
    @letters = @letters.where(aasm_state: params[:aasm_state]) if params[:aasm_state]

    @letters_month = current_user.letters.where(created_at: Time.now.beginning_of_month..Time.now).group(:aasm_state).count
  end

  def search_email
    @letters = Letter.all.order(id: :desc)
    @message = @letters.search_by_email(params[:q]).present? ? t(:record_already_exists) : t(:you_can_create_an_entry)
  end


  def show
  end

  def new
    @letter = Letter.new
  end

  def edit
  end

  def create
    @letter = current_user.letters.build(letter_params)
    if @letter.save
      redirect_to letters_path
    else
      render :new
    end
  end

  def update
    if @letter.update(letter_params)
      redirect_to @letter
    else
      render :edit
    end
  end

  def destroy
    if @letter.destroy
      redirect_to letters_path
    end
  end

  def to_cancel
    @letter.to_cancel!
    redirect_to @letter
  end

  def to_work
    @letter.to_work!
    redirect_to @letter
  end

  def to_completed
    @letter.to_completed!
    redirect_to @letter
  end

  def letter_statistics
    @letters = current_user.letters.last_half_year.order(:created_at).group_by { |q| q.created_at.strftime("%B") }
    .map do |month, letters|
      [
        month, letters.group_by(&:aasm_state)
          .map { |key, status| [key, status.count] }
      ]
    end
  end

  private

  def set_letter
    @letter = Letter.find(params[:id])
    redirect_to letters_path if @letter.nil?
  end

  def letter_params
    params.require(:letter).permit(:url_address, :email, :comment, :user_id, :aasm_state)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/letter_helper.rb
module LetterHelper
end

app/views/layouts/_navigation.html.slim
- if user_signed_in?
    nav.navbar.navbar-expand-lg.navbar-light[style="background-color: #ccc1c1;"]
      button.navbar-toggler aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo01" data-toggle="collapse" type="button"
        span.navbar-toggler-icon
      #navbarTogglerDemo01.collapse.navbar-collapse
        ul.navbar-nav.mr-auto
          li.nav-item
            = link_to t('.list_letter'), letters_path, class:'btn btn-secondary'
          li.nav-item
            = link_to t('.new_letter'), new_letter_path, class:'btn btn-secondary'
          li.nav-item
            = link_to t('.statistics_last_half_year'), letter_statistics_letters_path, method: :get, class:'btn btn-secondary'
          li.
            = form_tag(search_email_letters_path, method: :get, remote: true)
              = label_tag(:q, t('.search_email'))
              = text_field_tag(:q)
          .search-email
        form.my-2.my-lg-0
          = link_to t('.logout'), destroy_user_session_path, method: :delete, class:'btn btn-secondary'

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MailingOfLetters</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    title
      = t('.mail_sender')
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render "layouts/navigation"
    = yield
  footer.footer

app/views/letters/_filters.html.slim
.content.text-center
  = form_tag(letters_path, method: :get, class: 'filter-row') do
    = date_field(:date, :start_date)
    = date_field(:date, :end_date)
    = select_tag :aasm_state, options_for_select(@letters.aasm.states)
    .btn
      = submit_tag t('.check')

app/views/letters/_form.html.slim
= form_for @letter do |f|
  .form-group
  = f.label t('.email')
  = f.email_field :email, class: "form-control"
  .form-group
  = f.label t('.url_address')
  = f.text_field :url_address, class: "form-control"
  .form-group
  = f.label t('.comments')
  = f.text_area :comment, rows: 6, class: "form-control"
  .actions
    = f.submit t('.create_letter'), class:'btn btn-secondary'

app/views/letters/_jumbotron.html.slim
- if user_signed_in?
- else
  .container-main_screen
    .jumbotron.jumbotron-form
      h1.display-4
        = t('.hello')
      p.lead
        = t('.control_letters')
      hr.my-4
      p
        = t('.sign_in_or_register')
      p.lead
        = link_to t('.registration'), new_user_registration_path, class: "btn btn-dark"
        = link_to t('.login'), new_user_session_path, class: "btn btn-dark"

app/views/letters/_letter.html.slim
tr
  th scope="row"
    = letter.id
  td
    = letter.email
  td
    = letter.url_address
  td
    = letter.aasm_state
  td
    = letter.created_at
  td
    = letter.comment
  td
    = link_to t('.open'), letter, method: :get

app/views/letters/_show_form.html.slim
.container
  .row.columns_sig
    .col-md-2
      p = t('.url_address')
      = @letter.url_address
    .col-md-2
      p = t('.email')
      = @letter.email
    .col-md-3
      p = t('.comments')
      = @letter.comment
    .col-md-5
      p = t('.aasm_state')
      = @letter.aasm_state
      .row
      = link_to t('.to_cancel'), to_cancel_letter_path(@letter), method: :post, class: "btn btn-light" if ['new', 'in_work'].include?(@letter.aasm_state)
      = link_to t('.to_work'), to_work_letter_path(@letter), method: :post, class: "btn btn-light" if 'new'.include?(@letter.aasm_state)
      = link_to t('.to_completed'), to_completed_letter_path(@letter), method: :post, class: "btn btn-light" if 'in_work'.include?(@letter.aasm_state)

app/views/letters/index.html.slim
= render 'filters'
table.table.table-bordered
  thead.thead-dark
    tr
      th scope="col"
      th scope="col"
        = t ('.email')
      th scope="col"
        = t('.url_address')
      th scope="col"
        = t ('.aasm_state')
      th scope="col"
        = t ('.date_creating')
      th scope="col"
        = t ('.comments')
      th scope="col"
        = t ('.view_letter')
  tbody
    = render partial: 'letter', collection: @letters

h2 = t ('.statistics_month')
table.table.table-bordered
  thead.thead-dark
    tr
      th scope="col"
        = t('.canceled')
      th scope="col"
        = t('.completed')
      th scope="col"
        = t('.in_work')
      th scope="col"
        = t('.new')
    tr
  tbody
    - @letters_month.each do |key,value|
      tr
        td
          = value

app/views/letters/letter_statistics.html.slim
.row.m-2.justify-content-center
- @letters.each do |month, letters|
  .row.justify-content-center
    .alert-success.text-center = month
  - letters.each do |status, count|
    .row.justify-content-center
      .col-3.bg-light.text-right.col_stat #{t(status)} :
      .col-3.bg-light.col_stat = count

app/views/letters/new.html.slim
.card.jumbotron-form
  .card-header
    h2
      = t('.enter_data')
  .card-body
    = render 'form'
    .link
      = link_to t('.back'), letters_path, class: "btn btn-light"

app/views/letters/page.html.slim
= render 'jumbotron'

app/views/letters/search_email.js.erb
$('.search-email').html("<%= @message %>");

app/views/letters/show.html.slim
.card.jumbotron-form
  .card-header
  .card-body
    h5.card-title
    p.card-text
      = render 'show_form'
    .link_to_button.modal-footer
      = link_to t('.back'), letters_path, class: "btn btn-light"
      = link_to t('.delete'), letter_path, method: :delete, data: {confirm: t('.are_you_sure')}, class: "btn btn-light"